name: New feature request
description: Suggest an idea for the OVHcloud documentation.
body:
  - type: markdown
    attributes:
      value: |
        Provide a general summary of the feature request in the Title above
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the feature you request.              
        If so, you can create a sub-issue.  
        
        Before creating an issue, you can also check whether the feature you’re requesting is already included in our roadmaps:
        
        - [Cloud Roadmap & Changelog](https://github.com/orgs/ovh/projects/16)
        - [Hosting, Telco and Collaboration Roadmap & Changelog](https://github.com/orgs/ovh/projects/18)  

      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Relevant guide(s)
      description: | 
        Please let us know which guide(s) are concerned.    
        If your request is to create a new guide, please let us know the relevant universe and product.  
      placeholder: "- docs/{locale}/guides/{universe}/{product}/{slug}.mdx"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false