/**
 * Build theme/data/search-taxonomy.ts: the universe → product taxonomy that
 * drives the search filter pills, with per-locale display labels.
 *
 * The Pagefind search index tags each guide with `data-pagefind-filter`
 * values that are the STABLE PATH SLUGS (universe = 1st path segment, product
 * = 2nd). This file maps those slugs to the locale-translated labels shown on
 * the filter pills, and records which products belong to which universe so the
 * product pills can narrow to the selected universe.
 *
 * Source of truth: config/sidebar/index.md (the navigation tree) for structure
 * + slugs, and i18n.json for the localized labels (keyed by the same
 * `sidebar.gen.*` keys Rspress uses to render the sidebar). Emitting this at
 * build time keeps the client bundle free of the parser and index.md.
 *
 *   export const SEARCH_TAXONOMY: Record<Locale, {
 *     universes: { slug: string; label: string }[];
 *     products: Record<string, { slug: string; label: string }[]>;
 *   }> = { … };
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { parseIndexMd } from '../config/sidebar/parser';

const LOCALES = ['fr', 'en', 'de', 'es', 'it', 'pl', 'pt'] as const;
type Locale = (typeof LOCALES)[number];

const ROOT = path.resolve(import.meta.dirname, '..');
const SIDEBAR_DIR = path.join(ROOT, 'config/sidebar');
const DOCS_DIR = path.join(ROOT, 'docs');
const OUT = path.join(ROOT, 'theme/data/search-taxonomy.ts');

// Minimal shape of the parsed sidebar nodes we traverse.
interface Node {
  text?: string; // i18n key (sidebar.gen.*) for universe/product groups
  link?: string; // /guides/<universe>/<product>/…/<slug> on leaves
  items?: Node[];
}

const i18n: Record<string, Record<string, string>> = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'i18n.json'), 'utf-8'),
);

/** Resolve a sidebar.gen.* key to its label for a locale (falls back to EN). */
function label(key: string | undefined, locale: Locale): string | null {
  if (!key) return null;
  const entry = i18n[key];
  if (!entry) return null;
  return entry[locale] || entry.en || null;
}

/** First `/guides/…` leaf link found anywhere under a node. */
function firstLeafLink(node: Node): string | null {
  if (node.link && !node.items) return node.link;
  for (const child of node.items ?? []) {
    const l = firstLeafLink(child);
    if (l) return l;
  }
  return null;
}

/** Path segments after `/guides/`: [universe, product, …slug]. */
function segmentsOf(link: string): string[] {
  return link
    .replace(/^\/guides\//, '')
    .replace(/\.html$/, '')
    .split('/');
}

type Entry = { slug: string; label: string };

interface Taxonomy {
  universes: Entry[];
  products: Record<string, Entry[]>;
}

function buildForLocale(locale: Locale): Taxonomy {
  const { universes: tree } = parseIndexMd(
    path.join(SIDEBAR_DIR, 'index.md'),
    DOCS_DIR,
    locale,
  ) as unknown as { universes: Node[] };

  const universes: Entry[] = [];
  const products: Record<string, Entry[]> = {};
  const seenUniverse = new Set<string>();

  for (const uNode of tree) {
    const uLeaf = firstLeafLink(uNode);
    if (!uLeaf) continue; // universe with no guides — skip
    const uSlug = segmentsOf(uLeaf)[0];
    if (!uSlug) continue;
    const uLabel = label(uNode.text, locale) ?? uSlug;
    if (!seenUniverse.has(uSlug)) {
      universes.push({ slug: uSlug, label: uLabel });
      seenUniverse.add(uSlug);
    }

    // Direct product children of this universe.
    const seenProduct = new Set<string>();
    products[uSlug] ??= [];
    const list = products[uSlug];
    for (const pNode of uNode.items ?? []) {
      const pLeaf = firstLeafLink(pNode);
      if (!pLeaf) continue;
      const segs = segmentsOf(pLeaf);
      // A product needs a slug between universe and the final page slug.
      if (segs.length < 3) continue;
      const pSlug = segs[1];
      if (!pSlug || seenProduct.has(pSlug)) continue;
      seenProduct.add(pSlug);
      list.push({ slug: pSlug, label: label(pNode.text, locale) ?? pSlug });
    }
  }

  return { universes, products };
}

const taxonomy: Record<string, Taxonomy> = {};
for (const locale of LOCALES) {
  taxonomy[locale] = buildForLocale(locale);
}

const header = `// AUTO-GENERATED by scripts/build-search-taxonomy.ts — do not edit.
// Universe → product taxonomy for the search filter pills, per locale.
// Slugs match the data-pagefind-filter values injected at index time
// (see scripts/preprocess-html-worker.ts). Labels come from i18n.json.
export type SearchTaxonomyEntry = { slug: string; label: string };
export type SearchTaxonomy = {
  universes: SearchTaxonomyEntry[];
  products: Record<string, SearchTaxonomyEntry[]>;
};
export const SEARCH_TAXONOMY: Record<string, SearchTaxonomy> = `;

fs.writeFileSync(OUT, header + JSON.stringify(taxonomy, null, 2) + ';\n');

const en = taxonomy.en;
console.log(
  `✓ search-taxonomy.ts: ${en.universes.length} universes, ` +
    `${Object.values(en.products).reduce((n, p) => n + p.length, 0)} products (en)`,
);
