/**
 * Build theme/data/locale-availability.ts: per-route locale presence,
 * imported synchronously by theme/hooks/useLocaleAvailability so the
 * data is available at SSR time (i.e., the rendered <a href> already
 * points to the correct fallback URL for SEO robots).
 *
 *   export const LOCALE_AVAILABILITY: Record<string, string[]> = {
 *     "guides/web-cloud/internet/.../foo": ["fr"],
 *     "guides/public-cloud/databases/migrate-from-1az-to-3az": ["en"],
 *     ...
 *   };
 *
 * Only routes NOT available in all 7 locales are emitted; the hook
 * treats "absent from manifest" as "available everywhere".
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

const LOCALES = ['fr', 'en', 'de', 'es', 'it', 'pl', 'pt'] as const;
const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'theme/data/locale-availability.ts');

function walk(dir: string, out: string[] = []): string[] {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else if (e.name.endsWith('.mdx')) out.push(p);
  }
  return out;
}

function isResolvable(file: string): boolean {
  try {
    return fs.statSync(file).isFile();
  } catch {
    return false;
  }
}

const perLocale: Record<string, Set<string>> = {};
const union = new Set<string>();

for (const loc of LOCALES) {
  perLocale[loc] = new Set();
  const dir = path.join(ROOT, 'docs', loc, 'guides');
  if (!fs.existsSync(dir)) continue;
  for (const f of walk(dir)) {
    if (!isResolvable(f)) continue;
    const rel = f
      .replace(`${path.join(ROOT, 'docs', loc)}/`, '')
      .replace(/\.mdx$/, '');
    perLocale[loc].add(rel);
    union.add(rel);
  }
}

const manifest: Record<string, string[]> = {};
let partial = 0;
for (const rel of [...union].sort()) {
  const available = LOCALES.filter((loc) => perLocale[loc].has(rel));
  if (available.length === LOCALES.length) continue;
  manifest[rel] = available;
  partial++;
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
const body = `// AUTO-GENERATED by scripts/build-locale-availability.ts — do not edit.
// Maps each guide route to the locales where it has actual content.
// Routes available in all 7 locales are omitted (the consumer treats
// "absent from manifest" as "available everywhere").
export const LOCALE_AVAILABILITY: Record<string, string[]> = ${JSON.stringify(manifest, null, 2)};
`;
fs.writeFileSync(OUT, body);

console.log(`Total unique routes:           ${union.size}`);
console.log(`Fully localized (skipped):     ${union.size - partial}`);
console.log(`Partial (in manifest):         ${partial}`);
console.log(`Output: ${OUT} (${fs.statSync(OUT).size} bytes)`);
