/**
 * Build theme/data/product-availability.ts: the commercial-zone availability
 * of zoned products, baked from data/zones/product-availability.yaml so the
 * data is available synchronously in the bundle (same pattern as
 * scripts/build-locale-availability.ts).
 *
 *   export const PRODUCT_AVAILABILITY: Record<string, string[]> = {
 *     "sms": ["eu"],
 *     "exchange": ["eu", "ca"],
 *     ...
 *   };
 *
 * Consumers (Api / ManagerLink) use it to restrict the EU/CA region picker to
 * the zones where the referenced product actually exists. Products NOT listed
 * here are treated as available everywhere (no restriction).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { parse } from 'yaml';

const ROOT = path.resolve(import.meta.dirname, '..');
const SRC = path.join(ROOT, 'data/zones/product-availability.yaml');
const OUT = path.join(ROOT, 'theme/data/product-availability.ts');

// Fail-closed: this matrix decides whether EU-only products expose a CA region.
// A missing/malformed file is a real data error — fail loudly (caught in CI
// before shipping) rather than silently disabling the restrictions.
const map: Record<string, string[]> = {};
try {
  const doc = parse(fs.readFileSync(SRC, 'utf8')) as {
    products?: Record<string, { available_in?: string[] }>;
  };
  for (const [key, val] of Object.entries(doc.products ?? {})) {
    const zones = val?.available_in;
    if (Array.isArray(zones) && zones.length) {
      map[key] = zones;
    }
  }
} catch (err) {
  throw new Error(
    `Failed to read the product availability matrix at ${SRC}: ${(err as Error).message}\n` +
      'Fix the YAML (it gates EU-only products such as SMS) and re-run the build.',
  );
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
const body = `// AUTO-GENERATED by scripts/build-product-availability.ts — do not edit.
// Commercial-zone availability of zoned products, from the "products" section
// of data/zones/product-availability.yaml. Products absent from this map are
// treated as available in every zone (the consumer applies no restriction).
export const PRODUCT_AVAILABILITY: Record<string, string[]> = ${JSON.stringify(map, null, 2)};
`;
fs.writeFileSync(OUT, body);

console.log(`Products baked: ${Object.keys(map).length}`);
console.log(`Output: ${OUT} (${fs.statSync(OUT).size} bytes)`);
